name: datalad_binder

channels:
  - default
  - conda-forge

dependencies;
  - python=3.8.*
  - pip
  - datalad=0.15.*
  - pillow
  - nano
  - vim
  - tree
  - pip:
      - bash_kernel
      - cowsay
